# Generated by Django 3.2.16 on 2023-01-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_size_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantitySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_option', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='S', max_length=80)),
                ('quantity', models.IntegerField(default=1)),
                ('color_option', models.CharField(blank=True, choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Orange', 'Orange')], default='Red', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='size_option',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='S', max_length=80),
        ),
    ]
