# Generated by Django 3.2.16 on 2023-01-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230110_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantitysize',
            name='color_option',
        ),
        migrations.RemoveField(
            model_name='quantitysize',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='color_option',
            field=models.CharField(blank=True, choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Orange', 'Orange')], default='Red', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='has_color',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
